### ISSUE TITLE
devel-branch

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/wradlib-feedstock#15]
It turned out that it would be useful for testing purposes to have a devel-branch in the feedstock.

What steps are necessary to accomplish that? Just PR-ing to a new branch?

ping @conda-forge/core

**Comment by ocefpaf** [comment]
@kmuehlbauer this is a very common request and we already experimented with this in the `matplotlib` feedstock. However, we haven not settle in a "proper" way to do so. I will bring it up in today's meeting and let you know how it goes.

**Comment by jakirkham** [comment]
So this is definitely on the agenda, but we didn't get to it today. Next meeting should be in 3 weeks.

**Comment by kmuehlbauer** [comment]
@jakirkham It's not that pressing, so take your time to sort things out. :+1:

**Comment by jakirkham** [comment]
Thanks @kmuehlbauer. I appreciate your patience.

Though we haven't discussed this formally, I have raised an issue with `conda` to discuss the best way to control the installation of development releases in issue ( https://github.com/conda/conda/issues/3125 ). There has also been some discussion at conda-forge on prereleases ( https://github.com/conda-forge/conda-forge.github.io/issues/147 ) (this inspired the previous issue being raised). These would probably be worth getting acquainted with given your interest. Please feel free to share your thoughts as well.

**Comment by ocefpaf** [comment]
@kmuehlbauer matplotlib is doing this with a `devel` branch and publishing in a `rc` channel. See https://github.com/conda-forge/matplotlib-feedstock/blob/devel/.travis.yml#L44

I would standardize the channel to `devel` in all cases, even for release candidates, but maybe you can just copy matplotlib's strategy for now.

**Comment by kmuehlbauer** [comment]
@ocefpaf Thanks for the pointers. Having devel releases available via conda will help the project tremendously. So also users without deeper knowledge of git and repositories can use wradlib's devel packages.

**Comment by ocefpaf** [comment]
Agreed. We never settled on a simple way to do so in conda-forge. But at the end of the day it should be simple. `alpha`, `beta`, `rc` , `latest master` are all "`devel`" releases and should be in a `devel` channel. Tag the version and let the package fly :smile: 

(Or we will end up with those ugly and enigmatic PyPI release strings.)

**Comment by ocefpaf** [comment]
Closing this as stale. @kmuehlbauer we can create a branch and push to a label. People are using dev/devel/rc and that is pretty much your choice at this point.
(I kind of prefer `dev` though.)
