### ISSUE TITLE
Appveyor python 3.5 builds missing

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/wradlib-feedstock#18]
I just realized that the python 3.5 builds were removed from the matrix. While doing a quick search I found no explanation. Was this intended?

@ocefpaf It seemed to be introduced from commit c1338a1877536474e77573781773d9702f9de89b with #16. I somehow missed that before merging #16.

**Comment by ocefpaf** [comment]
Looks like a re-rendering issue. I saw that before. Let's try rerendering it again and if that does not work we can force add the missing part.

**Comment by kmuehlbauer** [comment]
OK, rerendering didn't touch the `appveyor.yml` at all.

**Comment by ocefpaf** [comment]
I suffered that in the past but I cannot recall the solution. Maybe @pelson remembers. We can just hard-code the missing matrix part for now.

**Comment by kmuehlbauer** [comment]
OK, see #19

**Comment by kmuehlbauer** [comment]
resolved, see #20
