### ISSUE TITLE
No windows uploads

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/wradlib-feedstock#23]
@conda-forge/core 

The latest appveyor builds [were successful](https://ci.appveyor.com/project/conda-forge/wradlib-feedstock/build/1.0.44/job/686kgq618u91bslw#L606), but the artifacts were [not uploaded](https://anaconda.org/conda-forge/wradlib/files?version=0.10.0).

Anything I can do? Perhaps rerendering?

**Comment by ocefpaf** [comment]
@kmuehlbauer I re-started to build to see if it is something transient. Next I would try re-rendering...

**Comment by kmuehlbauer** [comment]
@ocefpaf Thanks! That worked. Should have tested this myself. Next time...

**Comment by ocefpaf** [comment]
No problem.
