### ISSUE TITLE
BUG: new windows versions missing

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/wradlib-feedstock#4]
- wradlib v0.8.0 windows versions have been built, but not uploaded. 

@jjhelmus do you have you an idea, whats going on?

**Comment by ocefpaf** [comment]
> wradlib v0.8.0 windows versions have been built, but not uploaded.

Maybe #2?

**Comment by jjhelmus** [comment]
Yes, PR #2 updates the tokens used to upload the build packages to the conda-forge channel but will also break the Linux build.  I'll add a commit to that PR and merge it shortly.

**Comment by jjhelmus** [comment]
Windows conda packages, 32-bit and 64-bit, are available for both Python 2.7 and 3.4 on Anaconda.org in the conda-forge channel.

**Comment by pelson** [comment]
:+1:
